"""Initiales relationales Portalmodell.

Revision ID: 20260922_0001
Revises:
Create Date: 2026-09-22
"""
from alembic import op
import sqlalchemy as sa

revision = "20260922_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('identity_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('ip_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_identity_hash'), 'login_attempts', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_hash'), 'login_attempts', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_login_attempts_occurred_at'), 'login_attempts', ['occurred_at'], unique=False)
    op.create_table('presets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presets')),
    sa.UniqueConstraint('name', name=op.f('uq_presets_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=31), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('application_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'DELETED', name='tenant_status', native_enum=False), nullable=False),
    sa.Column('configuration_complete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_slug'), 'tenants', ['tenant_slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index('ix_audit_events_type_time', 'audit_events', ['event_type', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('group_memberships',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_memberships_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_memberships'))
    )
    op.create_table('portal_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('csrf_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portal_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_sessions'))
    )
    op.create_index(op.f('ix_portal_sessions_expires_at'), 'portal_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_portal_sessions_token_hash'), 'portal_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_portal_sessions_user_id'), 'portal_sessions', ['user_id'], unique=False)
    op.create_table('preset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('preset_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_preset_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], name=op.f('fk_preset_versions_preset_id_presets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preset_versions')),
    sa.UniqueConstraint('preset_id', 'version', name='uq_preset_version')
    )
    op.create_index(op.f('ix_preset_versions_preset_id'), 'preset_versions', ['preset_id'], unique=False)
    op.create_table('project_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_project_id', sa.BigInteger(), nullable=True),
    sa.Column('backup_document', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_project_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_templates'))
    )
    op.create_table('semaphore_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('semaphore_project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_semaphore_projects_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semaphore_projects')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_semaphore_projects_tenant_id'))
    )
    op.create_index(op.f('ix_semaphore_projects_semaphore_project_id'), 'semaphore_projects', ['semaphore_project_id'], unique=True)
    op.create_table('semaphore_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('proxy_url', sa.String(length=1000), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_semaphore_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semaphore_settings'))
    )
    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('semaphore_template_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('app', sa.String(length=40), nullable=False),
    sa.Column('survey_schema', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_task_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_templates')),
    sa.UniqueConstraint('tenant_id', 'semaphore_template_id', name='uq_task_template_remote')
    )
    op.create_index(op.f('ix_task_templates_tenant_id'), 'task_templates', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (group_id IS NULL)', name=op.f('ck_tenant_memberships_one_principal')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_tenant_memberships_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_memberships')),
    sa.UniqueConstraint('tenant_id', 'group_id', name='uq_tenant_membership_group'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_membership_user')
    )
    op.create_index(op.f('ix_tenant_memberships_group_id'), 'tenant_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('creation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'RESTORING', 'VERIFICATION_REQUIRED', 'SEMAPHORE_CREATED', 'COMPLETED', 'FAILED', name='creation_status', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('project_template_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('draft_data', sa.JSON(), nullable=False),
    sa.Column('prepared_backup', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('semaphore_project_id', sa.BigInteger(), nullable=True),
    sa.Column('semaphore_response', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('restore_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_creation_jobs_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], name=op.f('fk_creation_jobs_project_template_id_project_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_creation_jobs_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creation_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_creation_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_creation_jobs_status'), 'creation_jobs', ['status'], unique=False)
    op.create_table('task_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_template_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_start', sa.Boolean(), nullable=False),
    sa.Column('can_stop', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (group_id IS NULL)', name=op.f('ck_task_permissions_one_principal')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_task_permissions_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], name=op.f('fk_task_permissions_task_template_id_task_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_permissions')),
    sa.UniqueConstraint('task_template_id', 'group_id', name='uq_task_permission_group'),
    sa.UniqueConstraint('task_template_id', 'user_id', name='uq_task_permission_user')
    )
    op.create_index(op.f('ix_task_permissions_group_id'), 'task_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_permissions_task_template_id'), 'task_permissions', ['task_template_id'], unique=False)
    op.create_index(op.f('ix_task_permissions_user_id'), 'task_permissions', ['user_id'], unique=False)
    op.create_table('task_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], name=op.f('fk_task_policies_task_template_id_task_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_policies')),
    sa.UniqueConstraint('task_template_id', name=op.f('uq_task_policies_task_template_id'))
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('task_template_id', sa.Uuid(), nullable=False),
    sa.Column('started_by_id', sa.Uuid(), nullable=False),
    sa.Column('semaphore_task_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'STOPPED', 'UNKNOWN', name='task_run_status', native_enum=False), nullable=False),
    sa.Column('submitted_variables', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remote_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], name=op.f('fk_task_runs_started_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], name=op.f('fk_task_runs_task_template_id_task_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_task_runs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    sa.UniqueConstraint('tenant_id', 'semaphore_task_id', name='uq_task_run_remote')
    )
    op.create_index(op.f('ix_task_runs_started_by_id'), 'task_runs', ['started_by_id'], unique=False)
    op.create_index(op.f('ix_task_runs_status'), 'task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_task_runs_task_template_id'), 'task_runs', ['task_template_id'], unique=False)
    op.create_index(op.f('ix_task_runs_tenant_id'), 'task_runs', ['tenant_id'], unique=False)
    op.create_index('ix_task_runs_tenant_started', 'task_runs', ['tenant_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('variable_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('variable_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.Enum('FIXED', 'ENUM', 'INTEGER_RANGE', 'STRING', 'BOOLEAN', 'HIDDEN', name='rule_type', native_enum=False), nullable=False),
    sa.Column('fixed_value', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('regex_pattern', sa.String(length=500), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['task_policies.id'], name=op.f('fk_variable_rules_policy_id_task_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variable_rules')),
    sa.UniqueConstraint('policy_id', 'variable_name', name='uq_variable_rule_name')
    )
    op.create_index(op.f('ix_variable_rules_policy_id'), 'variable_rules', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_rules_policy_id'), table_name='variable_rules')
    op.drop_table('variable_rules')
    op.drop_index('ix_task_runs_tenant_started', table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_tenant_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_task_template_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_status'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_started_by_id'), table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_table('task_policies')
    op.drop_index(op.f('ix_task_permissions_user_id'), table_name='task_permissions')
    op.drop_index(op.f('ix_task_permissions_task_template_id'), table_name='task_permissions')
    op.drop_index(op.f('ix_task_permissions_group_id'), table_name='task_permissions')
    op.drop_table('task_permissions')
    op.drop_index(op.f('ix_creation_jobs_status'), table_name='creation_jobs')
    op.drop_table('creation_jobs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_group_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_task_templates_tenant_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_table('semaphore_settings')
    op.drop_index(op.f('ix_semaphore_projects_semaphore_project_id'), table_name='semaphore_projects')
    op.drop_table('semaphore_projects')
    op.drop_table('project_templates')
    op.drop_index(op.f('ix_preset_versions_preset_id'), table_name='preset_versions')
    op.drop_table('preset_versions')
    op.drop_index(op.f('ix_portal_sessions_user_id'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_token_hash'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_expires_at'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    op.drop_table('group_memberships')
    op.drop_index('ix_audit_events_type_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_tenant_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('presets')
    op.drop_index(op.f('ix_login_attempts_occurred_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_hash'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_identity_hash'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('groups')
    # ### end Alembic commands ###
