import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Network, Save } from 'lucide-react'
import { api } from '../../api'
import { Badge, Button, Card, Field, Loading, Notice, PageHeader, formatDate } from '../../components/ui'

type Config={configured:boolean;base_url:string;proxy_url?:string|null;last_test_success?:boolean|null;last_test_message?:string;last_tested_at?:string|null}
export function SemaphorePage(){
  const qc=useQueryClient(),query=useQuery({queryKey:['semaphore-config'],queryFn:()=>api<Config>('/admin/semaphore')})
  const [url,setUrl]=useState(''),[token,setToken]=useState(''),[proxy,setProxy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')
  useEffect(()=>{if(query.data){setUrl(query.data.base_url);setProxy(query.data.proxy_url||'')}},[query.data])
  const save=useMutation({mutationFn:()=>api<{message:string}>('/admin/semaphore',{method:'PUT',body:JSON.stringify({base_url:url,token:token||null,proxy_url:proxy||null}),headers:{'Content-Type':'application/json'}}),onSuccess:data=>{setMessage(data.message);setToken('');setError('');void qc.invalidateQueries({queryKey:['semaphore-config']})},onError:(e:Error)=>setError(e.message)})
  const test=useMutation({mutationFn:()=>api<{message:string}>('/admin/semaphore/test',{method:'POST'}),onSuccess:data=>{setMessage(data.message);setError('');void qc.invalidateQueries({queryKey:['semaphore-config']})},onError:(e:Error)=>setError(e.message)})
  if(query.isLoading)return <Loading/>
  return <><PageHeader title="Semaphore-Anbindung" description="Das Servicekonto bleibt ausschließlich im Backend; der Browser erhält keinen API-Token."/><div className="settings-grid"><Card><div className="card-heading"><div><h2>Verbindung</h2><p>Semaphore UI API-Basis und optionaler Firmenproxy</p></div>{query.data?.configured?<Badge tone={query.data.last_test_success?'success':'warning'}>Konfiguriert</Badge>:<Badge tone="warning">Offen</Badge>}</div>{error&&<Notice type="error">{error}</Notice>}{message&&<Notice type="success">{message}</Notice>}<div className="form-grid"><Field label="Semaphore Server-URL" help="Vollständige HTTP(S)-URL; /api kann enthalten sein."><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://semaphore.example.org"/></Field><Field label={query.data?.configured?'Neuer Service-Token (optional)':'Service-Token'} help="Wird verschlüsselt in PostgreSQL gespeichert und niemals zurückgegeben."><input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={query.data?.configured?'Unverändert lassen':'Bearer-Token'}/></Field><Field label="Firmenproxy (optional)"><input value={proxy} onChange={e=>setProxy(e.target.value)} placeholder="http://proxy.intern:8080"/></Field></div><div className="button-row"><Button loading={save.isPending} onClick={()=>save.mutate()} disabled={!url||(!query.data?.configured&&!token)}><Save size={16}/>Prüfen und speichern</Button><Button variant="secondary" loading={test.isPending} disabled={!query.data?.configured} onClick={()=>test.mutate()}><Network size={16}/>Verbindung testen</Button></div></Card>
    <Card><div className="connection-visual"><div className="server-node"><Network/></div><div className={`connection-line ${query.data?.last_test_success?'ok':''}`}/><div className="server-node"><CheckCircle2/></div></div><h3>{query.data?.last_test_message||'Noch keine Verbindung geprüft'}</h3><p className="muted">Letzte Prüfung: {formatDate(query.data?.last_tested_at)}</p><ul className="check-list"><li>GET-Redirects nur innerhalb desselben API-Ursprungs</li><li>Keine automatischen POST-Wiederholungen</li><li>TLS-Prüfung bleibt immer aktiv</li></ul></Card></div></>
}

