import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Check, ChevronLeft, ChevronRight, CircleCheck, Database, FileCheck2, Layers3, PackageCheck, Rocket, Settings2, ShieldCheck, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../../api'
import { Badge, Button, Card, Field, Loading, Notice, PageHeader } from '../../components/ui'
import type { User } from '../../types'

type Template={id:string;name:string;description:string;survey_catalog:Record<string,unknown[]>;task_templates:string[];environments:string[]}
type Preset={id:string;name:string;category:string;description:string}
type Group={id:string;name:string}
type CreationJob={id:string;status:string;draft_data:Draft;validation_result?:{errors:string[];warnings:string[]}|null;tenant_id?:string|null;last_error?:string|null}
type Draft={project_name:string;tenant_slug:string;display_name:string;description:string;application_id:string;database_type:string;dataset_id:string;ttl_minutes:number;task_template_names:string[];environment_names:string[];preset_ids:string[];access_assignments:Array<{user_id?:string;group_id?:string;role_code:string}>;create_default_policies:boolean;activate_after_creation:boolean}

const steps=[
  ['Vorlage','Projektquelle auswählen',Layers3],['Tenant','Stammdaten festlegen',Settings2],['Anwendung','Testdaten konfigurieren',Database],['Ressourcen','Tasks und Gruppen',PackageCheck],['Presets','Variablen ergänzen',FileCheck2],['Berechtigungen','Benutzer zuweisen',Users],['Validieren','Importvorschau prüfen',ShieldCheck],['Erstellen','Semaphore-Projekt anlegen',Rocket],
] as const
const initial:Draft={project_name:'',tenant_slug:'',display_name:'',description:'',application_id:'',database_type:'',dataset_id:'',ttl_minutes:60,task_template_names:[],environment_names:[],preset_ids:[],access_assignments:[],create_default_policies:true,activate_after_creation:false}

export function TenantWizardPage(){
  const navigate=useNavigate(),[step,setStep]=useState(0),[draft,setDraft]=useState<Draft>(initial),[job,setJob]=useState<CreationJob|null>(null),[templateId,setTemplateId]=useState(''),[error,setError]=useState('')
  const templates=useQuery({queryKey:['project-templates'],queryFn:()=>api<Template[]>('/admin/project-templates')})
  const presets=useQuery({queryKey:['presets'],queryFn:()=>api<Preset[]>('/admin/presets')})
  const users=useQuery({queryKey:['admin-users'],queryFn:()=>api<User[]>('/admin/users')})
  const groups=useQuery({queryKey:['admin-groups'],queryFn:()=>api<Group[]>('/admin/groups')})
  const selected=templates.data?.find(item=>item.id===templateId)
  const create=useMutation({mutationFn:()=>api<CreationJob>('/admin/creation-jobs',{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID(),project_template_id:templateId}),headers:{'Content-Type':'application/json'}})})
  const persist=async(existing?:CreationJob)=>{let current=existing||job;if(!current){current=await create.mutateAsync();setJob(current)}const updated=await api<CreationJob>(`/admin/creation-jobs/${current.id}`,{method:'PUT',body:JSON.stringify({draft_data:draft}),headers:{'Content-Type':'application/json'}});setJob(updated);return updated}
  const validate=useMutation({mutationFn:async()=>{const current=await persist();return api<CreationJob>(`/admin/creation-jobs/${current.id}/validate`,{method:'POST'})},onSuccess:value=>{setJob(value);setStep(6);setError('')},onError:(e:Error)=>setError(e.message)})
  const execute=useMutation({mutationFn:()=>api<CreationJob>(`/admin/creation-jobs/${job?.id}/execute`,{method:'POST',body:JSON.stringify({confirm_project_creation:true,allow_retry_after_verified_absence:false}),headers:{'Content-Type':'application/json'}}),onSuccess:value=>{setJob(value);setStep(7);setError('')},onError:(e:Error)=>setError(e.message)})
  const next=async()=>{setError('');if(step===0&&!templateId){setError('Bitte zuerst eine Projektvorlage auswählen.');return}if(step===1&&(!draft.project_name||!draft.tenant_slug||!draft.display_name)){setError('Projektname, Tenant-ID und Anzeigename sind erforderlich.');return}if(step===3&&!draft.task_template_names.length){setError('Mindestens ein Task Template ist erforderlich.');return}try{await persist();if(step===5){validate.mutate();return}setStep(value=>Math.min(7,value+1))}catch(reason){setError(reason instanceof Error?reason.message:'Entwurf konnte nicht gespeichert werden.') }}
  const chooseTemplate=(id:string)=>{setTemplateId(id);const item=templates.data?.find(row=>row.id===id);if(item)setDraft(value=>({...value,task_template_names:item.task_templates,environment_names:item.environments,application_id:String(item.survey_catalog.application_id?.[0]||''),database_type:String(item.survey_catalog.database_type?.[0]||''),dataset_id:String(item.survey_catalog.dataset_id?.[0]||'')}))}
  if(templates.isLoading||presets.isLoading||users.isLoading||groups.isLoading)return <Loading/>
  return <><PageHeader title="Tenant erstellen" description="Geführter, speicherbarer 8-Schritt-Prozess mit sicherer Importvorschau."/>
    <div className="wizard"><aside className="wizard-steps">{steps.map(([title,desc,Icon],index)=><button key={title} className={`${index===step?'active ':''}${index<step?'done ':''}`} onClick={()=>index<=step&&setStep(index)} disabled={index>step}><span className="step-circle">{index<step?<Check size={16}/>:<Icon size={16}/>}</span><span><strong>{index+1}. {title}</strong><small>{desc}</small></span></button>)}</aside>
      <Card className="wizard-content">{error&&<Notice type="error">{error}</Notice>}{job?.last_error&&<Notice type="error">{job.last_error}</Notice>}
        {step===0&&<WizardTemplate templates={templates.data||[]} selected={templateId} onSelect={chooseTemplate}/>} 
        {step===1&&<WizardTenant draft={draft} setDraft={setDraft}/>} 
        {step===2&&<WizardApplication draft={draft} setDraft={setDraft} template={selected}/>} 
        {step===3&&<WizardResources draft={draft} setDraft={setDraft} template={selected}/>} 
        {step===4&&<WizardPresets draft={draft} setDraft={setDraft} presets={presets.data||[]}/>} 
        {step===5&&<WizardAccess draft={draft} setDraft={setDraft} users={users.data||[]} groups={groups.data||[]}/>} 
        {step===6&&<WizardValidation job={job} draft={draft}/>} 
        {step===7&&<WizardResult job={job} onOpen={()=>job?.tenant_id&&navigate(`/admin/tenants/${job.tenant_id}`)}/>} 
        <div className="wizard-footer">{step>0&&step<7?<Button variant="secondary" onClick={()=>setStep(value=>value-1)}><ChevronLeft size={16}/>Zurück</Button>:<span/>}{step<6&&<Button onClick={()=>void next()} loading={create.isPending||validate.isPending}>Speichern & weiter<ChevronRight size={16}/></Button>}{step===6&&<Button onClick={()=>execute.mutate()} loading={execute.isPending} disabled={Boolean(job?.validation_result?.errors.length)}><Rocket size={16}/>Projekt verbindlich erstellen</Button>}{step===7&&<Button onClick={()=>job?.tenant_id&&navigate(`/admin/tenants/${job.tenant_id}`)}>Tenant öffnen</Button>}</div>
      </Card></div>
  </>
}

function WizardTitle({number,title,text}:{number:number;title:string;text:string}){return <div className="wizard-title"><span>Schritt {number} von 8</span><h2>{title}</h2><p>{text}</p></div>}
function WizardTemplate({templates,selected,onSelect}:{templates:Template[];selected:string;onSelect:(id:string)=>void}){return <><WizardTitle number={1} title="Projektvorlage auswählen" text="Das Originalprojekt bleibt unverändert; gearbeitet wird auf einer Kopie des Backups."/><div className="choice-grid">{templates.map(item=><button key={item.id} className={`choice-card ${selected===item.id?'selected':''}`} onClick={()=>onSelect(item.id)}><Layers3/><div><strong>{item.name}</strong><span>{item.description||`${item.task_templates.length} Task Templates`}</span></div>{selected===item.id&&<CircleCheck/>}</button>)}</div>{!templates.length&&<Notice type="info">Legen Sie zuerst unter „Projektvorlagen“ eine Vorlage an.</Notice>}</>}
function WizardTenant({draft,setDraft}:{draft:Draft;setDraft:(fn:(v:Draft)=>Draft)=>void}){const set=(key:keyof Draft,value:unknown)=>setDraft(v=>({...v,[key]:value}));return <><WizardTitle number={2} title="Tenant konfigurieren" text="Technische Kennung und Anzeigename werden getrennt geführt."/><div className="form-grid columns-2"><Field label="Semaphore-Projektname"><input value={draft.project_name} onChange={e=>set('project_name',e.target.value)}/></Field><Field label="Technische Tenant-ID" help="2–31 Zeichen: a-z, 0-9 und Bindestrich"><input value={draft.tenant_slug} onChange={e=>set('tenant_slug',e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))}/></Field><Field label="Anzeigename"><input value={draft.display_name} onChange={e=>set('display_name',e.target.value)}/></Field><Field label="Beschreibung"><input value={draft.description} onChange={e=>set('description',e.target.value)}/></Field></div></>}
function WizardApplication({draft,setDraft,template}:{draft:Draft;setDraft:(fn:(v:Draft)=>Draft)=>void;template?:Template}){const set=(key:keyof Draft,value:unknown)=>setDraft(v=>({...v,[key]:value}));const opts=(key:string)=>template?.survey_catalog[key]||[];return <><WizardTitle number={3} title="Anwendung und Testdaten" text="Auswahlwerte stammen ausschließlich aus den Surveys der gewählten Vorlage."/><div className="form-grid columns-2"><SelectOrInput label="Anwendung (application_id)" value={draft.application_id} options={opts('application_id')} onChange={v=>set('application_id',v)}/><SelectOrInput label="Datenbanktyp (database_type)" value={draft.database_type} options={opts('database_type')} onChange={v=>set('database_type',v)}/><SelectOrInput label="Datensatz (dataset_id)" value={draft.dataset_id} options={opts('dataset_id')} onChange={v=>set('dataset_id',v)}/><Field label="Standardlaufzeit (Minuten)"><input type="number" min={15} max={180} value={draft.ttl_minutes} onChange={e=>set('ttl_minutes',Number(e.target.value))}/></Field></div></>}
function SelectOrInput({label,value,options,onChange}:{label:string;value:string;options:unknown[];onChange:(v:string)=>void}){return <Field label={label}>{options.length?<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={String(v)} value={String(v)}>{String(v)}</option>)}</select>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder="Kein Survey-Wert vorhanden"/>}</Field>}
function WizardResources({draft,setDraft,template}:{draft:Draft;setDraft:(fn:(v:Draft)=>Draft)=>void;template?:Template}){const toggle=(key:'task_template_names'|'environment_names',name:string)=>setDraft(v=>({...v,[key]:v[key].includes(name)?v[key].filter(x=>x!==name):[...v[key],name]}));return <><WizardTitle number={4} title="Task Templates und Ressourcen" text="Nicht ausgewählte Inhalte werden nur aus der neuen Kopie entfernt."/><h3>Task Templates</h3><div className="check-grid">{template?.task_templates.map(name=><label key={name}><input type="checkbox" checked={draft.task_template_names.includes(name)} onChange={()=>toggle('task_template_names',name)}/><span>{name}</span></label>)}</div><h3>Variablengruppen</h3><div className="check-grid">{template?.environments.map(name=><label key={name}><input type="checkbox" checked={draft.environment_names.includes(name)} onChange={()=>toggle('environment_names',name)}/><span>{name}</span></label>)}</div><Notice type="info">Zeitpläne und Webhooks werden im Zielprojekt grundsätzlich nicht übernommen.</Notice></>}
function WizardPresets({draft,setDraft,presets}:{draft:Draft;setDraft:(fn:(v:Draft)=>Draft)=>void;presets:Preset[]}){const toggle=(id:string)=>setDraft(v=>({...v,preset_ids:v.preset_ids.includes(id)?v.preset_ids.filter(x=>x!==id):[...v.preset_ids,id]}));return <><WizardTitle number={5} title="Variablengruppen und Presets" text="Preset-Werte werden in die neue Tenant-Gruppe gemischt; tenant-spezifische Werte haben Vorrang."/><div className="choice-grid">{presets.map(item=><button key={item.id} className={`choice-card ${draft.preset_ids.includes(item.id)?'selected':''}`} onClick={()=>toggle(item.id)}><FileCheck2/><div><strong>{item.name}</strong><span>{item.category} · {item.description}</span></div>{draft.preset_ids.includes(item.id)&&<Check/>}</button>)}</div></>}
function WizardAccess({draft,setDraft,users,groups}:{draft:Draft;setDraft:(fn:(v:Draft)=>Draft)=>void;users:User[];groups:Group[]}){const toggle=(kind:'user_id'|'group_id',id:string)=>setDraft(v=>{const has=v.access_assignments.some(x=>x[kind]===id);return{...v,access_assignments:has?v.access_assignments.filter(x=>x[kind]!==id):[...v.access_assignments,{[kind]:id,role_code:'operator'}]}});return <><WizardTitle number={6} title="Benutzer und Berechtigungen" text="Operatoren dürfen die initial freigegebenen Tasks sehen, starten und abbrechen."/><div className="access-columns"><div><h3>Benutzer</h3><div className="check-grid">{users.filter(u=>u.is_active).map(user=><label key={user.id}><input type="checkbox" checked={draft.access_assignments.some(x=>x.user_id===user.id)} onChange={()=>toggle('user_id',user.id)}/><span>{user.display_name}<small>{user.email}</small></span></label>)}</div></div><div><h3>Gruppen</h3><div className="check-grid">{groups.map(group=><label key={group.id}><input type="checkbox" checked={draft.access_assignments.some(x=>x.group_id===group.id)} onChange={()=>toggle('group_id',group.id)}/><span>{group.name}</span></label>)}</div></div></div><label className="toggle-row"><input type="checkbox" checked={draft.create_default_policies} onChange={e=>setDraft(v=>({...v,create_default_policies:e.target.checked}))}/><span><strong>Sichere Initial-Policies erzeugen</strong><small>Tenant/App/DB fest, Datensatz als Enum, TTL 15–180, Host-Port 0</small></span></label><label className="toggle-row"><input type="checkbox" checked={draft.activate_after_creation} onChange={e=>setDraft(v=>({...v,activate_after_creation:e.target.checked}))}/><span><strong>Nach erfolgreicher Konfiguration aktivieren</strong><small>Nur wenn Projekt und mindestens eine Policy vollständig sind</small></span></label></>}
function WizardValidation({job,draft}:{job:CreationJob|null;draft:Draft}){const result=job?.validation_result;return <><WizardTitle number={7} title="Konfiguration validieren" text="Die Vorschau wurde lokal erzeugt und mit der aktuellen Semaphore-Projektliste abgeglichen."/><div className="review-grid"><div><span>Projektname</span><strong>{draft.project_name}</strong></div><div><span>Tenant</span><strong>{draft.tenant_slug}</strong></div><div><span>Tasks</span><strong>{draft.task_template_names.length}</strong></div><div><span>Zugriffe</span><strong>{draft.access_assignments.length}</strong></div></div>{result?.errors.length?<Notice type="error"><strong>Validierung fehlgeschlagen</strong><ul>{result.errors.map(item=><li key={item}>{item}</li>)}</ul></Notice>:<Notice type="success">Struktur- und Verbindungsprüfung bestanden. Das Quellprojekt wird nicht verändert.</Notice>}{Boolean(result?.warnings.length)&&<Notice type="info"><ul>{result?.warnings.map(item=><li key={item}>{item}</li>)}</ul></Notice>}</>}
function WizardResult({job,onOpen}:{job:CreationJob|null;onOpen:()=>void}){return <div className="success-screen"><div className="success-icon"><CircleCheck size={42}/></div><span>ERSTELLUNG ABGESCHLOSSEN</span><h2>Tenant-Projekt wurde registriert</h2><p>Semaphore-Projekt und Portalzuordnung wurden erfolgreich verknüpft. Prüfen Sie jetzt Key Store, Repository und Inventory.</p><div className="review-grid"><div><span>Status</span><strong>{job?.status}</strong></div><div><span>Portal-Tenant</span><strong>{job?.tenant_id}</strong></div></div><Button onClick={onOpen}>Tenant öffnen</Button></div>}

